# Generated by Django 5.2.5 on 2025-08-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('idMotorista', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=40)),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=20)),
                ('dataEntrada', models.DateField()),
            ],
        ),
    ]
