# Generated by Django 5.2.5 on 2025-08-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('cnpj', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('telefone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('idEndereco', models.AutoField(primary_key=True, serialize=False)),
                ('cidade', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('rua', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('cep', models.IntegerField(default='0000000000')),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('idMotorista', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.IntegerField()),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.IntegerField()),
                ('email', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=45)),
                ('codigoCnh', models.CharField(max_length=45)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routerifc.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('idPassageiros', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=45)),
                ('nome', models.CharField(max_length=30)),
                ('dataNascimento', models.DateField()),
                ('cpf', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('nomeResponsavel', models.CharField(max_length=30)),
                ('cpfResponsavel', models.IntegerField()),
                ('telefoneResponsavel', models.IntegerField()),
                ('endereco', models.ManyToManyField(related_name='passageiros', to='routerifc.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Rotas',
            fields=[
                ('idRotas', models.AutoField(primary_key=True, serialize=False)),
                ('horarios', models.TimeField()),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='routerifc.motorista')),
            ],
        ),
        migrations.AddField(
            model_name='endereco',
            name='rotas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='routerifc.rotas'),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('idCarro', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=30)),
                ('capacidade', models.IntegerField()),
                ('modelo', models.CharField(max_length=45)),
                ('motoristas', models.ManyToManyField(related_name='veiculos', to='routerifc.motorista')),
                ('passageiros', models.ManyToManyField(related_name='veiculos', to='routerifc.passageiro')),
            ],
        ),
        migrations.AddField(
            model_name='rotas',
            name='veiculos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='routerifc.veiculo'),
        ),
    ]
