# Generated by Django 5.2.5 on 2025-09-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerifc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passageiro',
            name='endereco',
            field=models.ManyToManyField(blank=True, null=True, related_name='passageiros', to='routerifc.endereco'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='passageiros',
            field=models.ManyToManyField(blank=True, null=True, related_name='veiculos', to='routerifc.passageiro'),
        ),
    ]
