# Generated by Django 5.2.5 on 2025-08-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerifc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(default=0, max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('idCarro', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=30)),
                ('capacidade', models.IntegerField()),
                ('motoristas', models.ManyToManyField(related_name='veiculos', to='routerifc.motorista')),
            ],
        ),
    ]
