# Generated by Django 5.2.5 on 2025-08-08 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerifc', '0002_motorista_cpf_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('email', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='motorista',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routerifc.empresa'),
        ),
    ]
