# Generated by Django 5.2.5 on 2025-09-11 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerifc', '0002_alter_passageiro_endereco_alter_veiculo_passageiros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passageiro',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='rotas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endereco', to='routerifc.rotas'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='routerifc.empresa'),
        ),
        migrations.AlterField(
            model_name='rotas',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='routerifc.motorista'),
        ),
        migrations.AlterField(
            model_name='rotas',
            name='veiculos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='routerifc.veiculo'),
        ),
    ]
