# Generated by Django 5.2.5 on 2025-08-08 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerifc', '0003_empresa_motorista_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotas',
            fields=[
                ('idRotas', models.AutoField(primary_key=True, serialize=False)),
                ('horarios', models.TimeField()),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='routerifc.motorista')),
            ],
        ),
    ]
