# Generated by Django 5.2.5 on 2025-08-08 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerifc', '0004_rotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotas',
            name='veiculos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='routerifc.veiculo'),
            preserve_default=False,
        ),
    ]
