# Generated by Django 5.2.5 on 2025-08-08 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerifc', '0005_rotas_veiculos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('idEndereco', models.AutoField(primary_key=True, serialize=False)),
                ('cidade', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('rua', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('complemento', models.TextField(blank=True, null=True)),
                ('rotas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='routerifc.rotas')),
            ],
        ),
    ]
