# Generated by Django 5.2.6 on 2025-09-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerifc', '0005_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='atualizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='latitude_atual',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='longitude_atual',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='rota_ativa',
            field=models.BooleanField(default=False),
        ),
    ]
