# Generated by Django 5.2.4 on 2025-09-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerifc', '0005_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='cpfResponsavel',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='telefoneResponsavel',
            field=models.CharField(max_length=20),
        ),
    ]
