# Generated by Django 5.2.6 on 2025-09-17 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerifc', '0006_motorista_atualizado_em_motorista_latitude_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='rotas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='endereco', to='routerifc.rotas'),
        ),
    ]
