# Generated by Django 5.2.5 on 2025-08-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerifc', '0006_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passageiros',
            fields=[
                ('idPassageiros', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=40)),
                ('dataEntrada', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.ManyToManyField(related_name='passageiros', to='routerifc.endereco')),
            ],
        ),
        migrations.AddField(
            model_name='veiculo',
            name='passageiros',
            field=models.ManyToManyField(related_name='veiculos', to='routerifc.passageiros'),
        ),
    ]
