# Generated by Django 5.2.6 on 2025-09-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerifc', '0007_make_rotas_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passageiro',
            name='endereco',
            field=models.ManyToManyField(blank=True, related_name='passageiros', to='routerifc.endereco'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='passageiros',
            field=models.ManyToManyField(blank=True, related_name='veiculos', to='routerifc.passageiro'),
        ),
    ]
