# Generated by Django 5.2.5 on 2025-08-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerifc', '0007_passageiros_veiculo_passageiros'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageiros',
            name='nome',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
