# Generated by Django 5.2.5 on 2025-08-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routerifc', '0008_passageiros_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passageiros',
            new_name='Passageiro',
        ),
    ]
