# Generated by Django 5.2.4 on 2025-09-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerifc', '0008_fix_manytomany_warnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
